#!/usr/bin/env python3
"""Builds automations_data.json — the source of truth for Automation-Bazaar.
Seeded with real, attributed automations. The Gemini goal grows it toward 5000+.
"""
import json, os, re

CATEGORIES = [
    {"slug": "n8n",            "label": "n8n"},
    {"slug": "make-com",       "label": "Make.com"},
    {"slug": "zapier",         "label": "Zapier"},
    {"slug": "scripts",        "label": "Automation Scripts"},
    {"slug": "schedules-cron", "label": "Schedules & Cron"},
    {"slug": "other-platforms","label": "Other Platforms"},
]

# (cat, title, author, source, rating, description, useWhen, trigger, steps[], note, keywords[])
SEED = [
 # ---------------- n8n ----------------
 ("n8n", "AI email auto-responder (Gmail + GPT-4/Claude)", "enescingoz (awesome-n8n-templates)", "https://github.com/enescingoz/awesome-n8n-templates", 4.8,
  "Reads incoming Gmail, classifies by topic/urgency with an LLM, and drafts a context-aware reply for review.",
  "When your inbox needs triage and first-draft replies at scale.",
  "New email in Gmail",
  ["Trigger on new Gmail message","Classify topic + urgency with GPT-4/Claude","Draft a reply from a template + context","Save as draft or send after approval"],
  "Keep a human-approval step until reply quality is trusted.",
  ["gmail","email triage","llm","auto-reply"]),
 ("n8n", "RAG chatbot over a company knowledge base", "n8n Team (templates)", "https://n8n.io/workflows/", 4.9,
  "Retrieval-augmented chatbot that embeds your docs into a vector store (Pinecone/Qdrant/Supabase) and answers from them.",
  "When you need a grounded assistant that answers from your own content.",
  "Chat message / webhook",
  ["Ingest + chunk documents","Embed and upsert to a vector DB","On query, retrieve top-k context","Answer with the LLM citing sources"],
  "Re-index on document changes to avoid stale answers.",
  ["rag","vector store","chatbot","pinecone","qdrant"]),
 ("n8n", "Blog post → LinkedIn/X/newsletter repurposer", "enescingoz (awesome-n8n-templates)", "https://github.com/enescingoz/awesome-n8n-templates", 4.7,
  "Turns one blog post into platform-tailored LinkedIn posts, tweets, and an email newsletter draft.",
  "When you want to repurpose long-form content into many channels.",
  "New blog post (RSS/CMS)",
  ["Fetch the new post","Summarize + rewrite per platform with an LLM","Generate variants","Queue/schedule to each channel"],
  "Add brand-voice guidelines to the prompt for consistency.",
  ["content repurposing","social media","linkedin","newsletter"]),
 ("n8n", "Telegram AI assistant bot", "n8n community", "https://n8n.io/workflows/", 4.6,
  "A Telegram bot backed by an LLM with memory, for Q&A and task commands.",
  "When you want a personal assistant in Telegram.",
  "Telegram message",
  ["Receive Telegram update","Load short-term memory","Call the LLM","Reply in chat + persist memory"],
  "Scope the bot to allowed chat IDs to prevent abuse.",
  ["telegram","bot","assistant","memory"]),
 ("n8n", "Invoice/PDF data extraction to Google Sheets", "Intuz (templates roundup)", "https://www.intuz.com/blog/best-n8n-workflow-templates", 4.6,
  "Parses invoice PDFs, extracts line items with an LLM/OCR, and appends structured rows to Google Sheets.",
  "When you process many invoices/receipts manually.",
  "New file in Drive/email attachment",
  ["Detect new PDF","OCR / LLM-extract fields","Validate totals","Append row to Google Sheets"],
  "Add a confidence threshold and route low-confidence docs for review.",
  ["ocr","invoices","google sheets","data extraction"]),
 ("n8n", "Daily AI news digest to email/Slack", "ai-rockstars (templates roundup)", "https://ai-rockstars.com/the-10-best-n8n-workflow-templates-for-automation/", 4.5,
  "Aggregates RSS/news sources, summarizes with an LLM, and sends a daily digest.",
  "When you want a curated morning briefing.",
  "Schedule (daily)",
  ["Pull configured feeds","De-dupe + rank items","Summarize with the LLM","Send digest to email/Slack"],
  "Cap item count to keep the digest skimmable.",
  ["rss","digest","summarization","newsletter"]),
 ("n8n", "Lead enrichment + CRM sync", "Goodspeed Studio (agency templates)", "https://goodspeed.studio/blog/n8n-templates", 4.6,
  "Enriches new leads (company, role, socials) and upserts them into the CRM with a Slack alert.",
  "When inbound leads need enrichment before sales follow-up.",
  "New lead (form/webhook)",
  ["Receive lead","Enrich via data provider","Upsert to CRM (HubSpot/Pipedrive)","Notify sales in Slack"],
  "Respect data-privacy rules for enrichment providers.",
  ["lead enrichment","crm","hubspot","sales"]),
 ("n8n", "WhatsApp inbound automation", "n8n community", "https://n8n.io/workflows/", 4.4,
  "Handles inbound WhatsApp messages, routes by intent, and replies or creates a ticket.",
  "When you support customers over WhatsApp.",
  "WhatsApp message",
  ["Receive message","Detect intent with the LLM","Reply or open a ticket","Log to CRM"],
  "Follow WhatsApp Business policy for automated messaging.",
  ["whatsapp","support","routing","tickets"]),

 # ---------------- Make.com ----------------
 ("make-com", "Form submission → CRM contact → Slack notify", "Make Templates", "https://www.make.com/en/templates", 4.6,
  "Watches a form, creates/updates a CRM contact, and posts a notification to Slack.",
  "When new form leads must reach your CRM and team instantly.",
  "New form submission",
  ["Watch form (Typeform/Tally)","Search/create CRM contact","Map fields","Post to Slack channel"],
  "Use a router to branch on lead source.",
  ["make","forms","crm","slack"]),
 ("make-com", "RSS → AI summary → Notion", "Make Templates", "https://www.make.com/en/templates", 4.5,
  "Pulls new RSS items, summarizes with an AI module, and stores them in a Notion database.",
  "When you build a curated reading database.",
  "New RSS item",
  ["Watch RSS feed","Summarize with AI","Create Notion page","Tag by topic"],
  "Add a dedupe filter on item GUID.",
  ["make","rss","notion","summary"]),
 ("make-com", "Email parser → Airtable", "Make Templates", "https://www.make.com/en/templates", 4.4,
  "Parses structured emails (orders, alerts) and writes records into Airtable.",
  "When inbound emails carry data you need in a table.",
  "New email matching a filter",
  ["Watch mailbox","Parse fields (text parser)","Map to Airtable schema","Create/Update record"],
  "Build the parser against several real samples.",
  ["make","email parsing","airtable"]),
 ("make-com", "Webhook payment → tag CRM contact", "Make Templates", "https://www.make.com/en/templates", 4.5,
  "Receives a payment webhook, finds the customer, and tags/segments them in the CRM.",
  "When purchases should trigger lifecycle segmentation.",
  "Payment webhook (Stripe)",
  ["Receive webhook","Lookup contact","Add tag / move stage","Trigger follow-up sequence"],
  "Verify webhook signatures before processing.",
  ["make","stripe","webhook","crm"]),
 ("make-com", "Multi-channel social scheduler", "Make Templates", "https://www.make.com/en/templates", 4.4,
  "Takes a content row and publishes/schedules it across several social platforms.",
  "When you publish the same content to many channels.",
  "New row in content sheet",
  ["Watch content sheet","Format per platform","Publish/schedule","Mark row as posted"],
  "Stagger post times to avoid duplicate-content penalties.",
  ["make","social media","scheduling"]),

 # ---------------- Zapier ----------------
 ("zapier", "Brand mention on X → Slack alert", "Databox (21 zaps)", "https://databox.com/zapier-examples", 4.6,
  "Notifies a Slack channel whenever your brand is mentioned on X/Twitter.",
  "When you want real-time social listening.",
  "New tweet matching search",
  ["Trigger on matching tweet","Filter noise","Format message","Post to Slack"],
  "Use precise search operators to cut false positives.",
  ["zapier","twitter","slack","social listening"]),
 ("zapier", "New lead → HubSpot + Slack notify", "Databox (21 zaps)", "https://databox.com/zapier-examples", 4.7,
  "Adds new leads to HubSpot and pings sales in Slack.",
  "When inbound leads must reach CRM + team fast.",
  "New lead (form/ads)",
  ["Trigger on new lead","Create/update HubSpot contact","Notify Slack","Optionally start a sequence"],
  "Map UTM fields for attribution.",
  ["zapier","hubspot","leads","slack"]),
 ("zapier", "Incoming email → task/to-do", "Zapier (examples)", "https://zapier.com/blog/zapier-automation-examples/", 4.5,
  "Turns starred/labeled emails into tasks in your project tool.",
  "When email is your informal task inbox.",
  "New labeled email",
  ["Trigger on labeled email","Extract subject/body","Create task (Todoist/Asana)","Link back to email"],
  "Use a dedicated label to avoid task spam.",
  ["zapier","email","tasks","todoist"]),
 ("zapier", "Form submission → Google Sheets row", "Zapier (examples)", "https://zapier.com/blog/zapier-automation-examples/", 4.4,
  "Appends every new form response as a row in Google Sheets.",
  "When you need a simple data log of submissions.",
  "New form submission",
  ["Trigger on submission","Map fields to columns","Append row","Optional Slack notify"],
  "Keep the sheet header in sync with form fields.",
  ["zapier","forms","google sheets"]),
 ("zapier", "Calendly booking → CRM + reminder", "Ringover (zap examples)", "https://www.ringover.com/blog/zapier-workflow-automation", 4.5,
  "On a new Calendly booking, creates/updates a CRM record and schedules reminders.",
  "When meetings should sync to CRM automatically.",
  "New Calendly event",
  ["Trigger on booking","Upsert CRM contact","Create calendar reminder","Send confirmation"],
  "Handle reschedules/cancellations with extra triggers.",
  ["zapier","calendly","crm","reminders"]),
 ("zapier", "Sync unsubscribes across email systems", "Getmagical (best zaps)", "https://www.getmagical.com/blog/best-zapier-automations", 4.3,
  "Propagates an unsubscribe in one tool to all other email systems for compliance.",
  "When you run multiple email platforms.",
  "New unsubscribe",
  ["Trigger on unsubscribe","Find contact in each system","Mark unsubscribed everywhere","Log change"],
  "Critical for CAN-SPAM/GDPR consistency.",
  ["zapier","email","compliance","unsubscribe"]),

 # ---------------- Automation Scripts ----------------
 ("scripts", "Nightly restic/rsync backup", "Community (restic docs)", "https://restic.readthedocs.io/", 4.7,
  "Encrypted incremental backups of key paths to local + remote, with pruning and a status notification.",
  "When you need reliable, versioned backups.",
  "Cron (nightly)",
  ["Snapshot configured paths","Push to repo (local + S3/B2)","Prune by retention policy","Notify on success/failure"],
  "Test restores regularly — an untested backup is a hope, not a backup.",
  ["backup","restic","rsync","cron"]),
 ("scripts", "Let's Encrypt cert auto-renew + reload", "Community (certbot)", "https://eff-certbot.readthedocs.io/", 4.6,
  "Renews TLS certificates and reloads the web server only when a cert actually changes.",
  "When you manage your own TLS certs.",
  "Cron / systemd timer",
  ["Run certbot renew","Detect changed certs","Reload nginx/apache","Alert on failure"],
  "Use --deploy-hook so reloads happen only on renewal.",
  ["tls","certbot","lets encrypt","nginx"]),
 ("scripts", "Docker prune + unhealthy-container restart", "Community", "https://docs.docker.com/", 4.4,
  "Frees disk by pruning dangling images/volumes and restarts containers failing healthchecks.",
  "When long-running Docker hosts drift or bloat.",
  "Cron (hourly/daily)",
  ["Prune dangling images/volumes","List unhealthy containers","Restart them","Report reclaimed space"],
  "Exclude volumes you must keep from pruning.",
  ["docker","prune","healthcheck","ops"]),
 ("scripts", "Log rotation + compress + ship", "Community (logrotate)", "https://linux.die.net/man/8/logrotate", 4.3,
  "Rotates and compresses app logs and ships archives to object storage.",
  "When app logs grow unbounded.",
  "Cron (daily)",
  ["Rotate + compress logs","Upload archives to storage","Apply retention","Verify free space"],
  "Coordinate with the app's own log handling to avoid gaps.",
  ["logs","logrotate","retention","ops"]),

 # ---------------- Schedules & Cron ----------------
 ("schedules-cron", "Daily database backup cron", "Community", "https://www.postgresql.org/docs/current/backup-dump.html", 4.7,
  "Scheduled pg_dump/mysqldump with rotation and off-box copy.",
  "Essential alongside any data-changing workflow.",
  "Cron (daily, off-peak)",
  ["Dump database","Compress + timestamp","Copy off-box","Rotate old dumps"],
  "Store at least one copy off the host.",
  ["cron","backup","postgres","mysql"]),
 ("schedules-cron", "Hourly inbox/RSS poll", "Community", "https://crontab.guru/", 4.2,
  "A cron schedule that polls inboxes/feeds to drive downstream automations.",
  "When a workflow needs periodic fetches.",
  "Cron (hourly)",
  ["Fetch new items","Hand off to the workflow","Record last-seen cursor","Backoff on errors"],
  "Keep a cursor to avoid reprocessing.",
  ["cron","polling","rss","schedule"]),
 ("schedules-cron", "Weekly dependency update + PR", "Renovate/Dependabot pattern", "https://docs.renovatebot.com/", 4.6,
  "Scheduled dependency upgrades that open a PR and run CI before merge.",
  "When you want safe, steady dependency hygiene.",
  "Schedule (weekly)",
  ["Scan manifests for updates","Open grouped PRs","Run CI","Auto-merge if green"],
  "Group minor/patch updates to reduce PR noise.",
  ["renovate","dependabot","ci","schedule"]),

 # ---------------- Other Platforms ----------------
 ("other-platforms", "GitHub Actions scheduled CI sweep", "GitHub Docs", "https://docs.github.com/actions", 4.6,
  "A scheduled workflow that runs tests/lint/security sweeps and reports results.",
  "When you want recurring checks beyond push events.",
  "schedule: cron in workflow",
  ["Define on.schedule cron","Run test/lint/security jobs","Upload artifacts","Notify on failure"],
  "Scheduled runs use the default branch's workflow file.",
  ["github actions","ci","schedule","cron"]),
 ("other-platforms", "Airflow daily ETL DAG", "Apache Airflow Docs", "https://airflow.apache.org/", 4.5,
  "An orchestrated daily extract-transform-load pipeline with retries and alerting.",
  "When data pipelines need dependable scheduling + retries.",
  "Airflow schedule (daily)",
  ["Extract from sources","Transform/validate","Load to warehouse","Alert on SLA miss"],
  "Make tasks idempotent so retries are safe.",
  ["airflow","etl","dag","data pipeline"]),
]

def slugify(s):
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return s[:60]

def build():
    loops = []
    counters = {}
    for cat, title, author, source, rating, desc, usewhen, trigger, steps, note, kw in SEED:
        counters[cat] = counters.get(cat, 0) + 1
        num = f"{len(loops)+1:03d}"
        label = next(c["label"] for c in CATEGORIES if c["slug"] == cat)
        loops.append({
            "number": num,
            "slug": slugify(title),
            "title": title,
            "author": author,
            "source": source,
            "license": "See source",
            "averageRating": rating,
            "category": {"label": label, "slug": cat},
            "platform": label,
            "description": desc,
            "useWhen": usewhen,
            "trigger": trigger,
            "steps": steps,
            "implementationNote": note,
            "keywords": kw,
            "published": "2026-06-20",
            "modified": "2026-06-20",
            "reviews": [],
        })
    data = {
        "updated": "2026-06-20",
        "loopCount": len(loops),
        "categories": CATEGORIES,
        "loops": loops,
    }
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "automations_data.json")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Wrote {out} with {len(loops)} automations across {len(CATEGORIES)} categories.")

if __name__ == "__main__":
    build()
